---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-broker-rhel8
spec:
  targetNamespaces:
  - amq-mqtt
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker-rhel8
spec:
  channel: 7.x
  installPlanApproval: Automatic
  name: amq-broker-rhel8
  source: redhat-operators
  sourceNamespace: openshift-marketplace
