apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: amq-mqtt-build-and-deploy
spec:
  params:
    - name: APP_NAME
      value: amq-mqtt
    - name: GIT_REPO
      value: 'https://github.com/pittar/amq-mqtt.git'
  pipelineRef:
    name: amq-mqtt-build-and-deploy
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: pipeline-workspaces
