apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    tekton.dev/pipeline: amq-mqtt
  name: pipeline-workspaces
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
