---
apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemisAddress
metadata:
  name: incoming1
spec:
  addressName: goc_cpc.std.apps.dia.events.newstop.item.wc.pdt1.route.pdt1
  routingType: multicast
  queueName: goc_cpc.std.apps.dia.events.newstop.item.wc.pdt1.route.pdt1
---
apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemisAddress
metadata:
  name: outgoing1
spec:
  addressName: reply.wc.pdt1.route.pdt1
  routingType: anycast
  queueName: reply.wc.pdt1.route.pdt1
---
apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemisAddress
metadata:
  name: incoming2
spec:
  addressName: goc_cpc.std.apps.dia.events.newstop.item.wc.pdt2.route.pdt2
  routingType: multicast 
  queueName: goc_cpc.std.apps.dia.events.newstop.item.wc.pdt2.route.pdt2
---
apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemisAddress
metadata:
  name: outgoing2
spec:
  addressName: reply.wc.pdt2.route.pdt2
  routingType: anycast
  queueName: reply.wc.pdt2.route.pdt2